<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Playing in - JAKARTA</name>
   <tag></tag>
   <elementGuidId>681fbdb4-6542-4ddb-b218-2d6538edb7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu_nav_bar']/ul[2]/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28f22a83-81de-4bdd-9b6e-d596cca82994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>gui.list_city.php?sid=</value>
      <webElementGuid>4fd871ba-34c3-459e-8722-a415437c0dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_bar-animate</value>
      <webElementGuid>5b78edfb-478b-443b-92ae-3bdd0fd65abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Playing in - JAKARTA</value>
      <webElementGuid>41aa975a-9a8f-4562-8474-c7f5a2192cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_nav_bar&quot;)/ul[@class=&quot;nav navbar-nav navbar-left&quot;]/li[@class=&quot;nav_bar-animate&quot;]/a[@class=&quot;nav_bar-animate&quot;]</value>
      <webElementGuid>bbd273d8-9f84-40e8-80ca-a53a9f65fadd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu_nav_bar']/ul[2]/li[4]/a</value>
      <webElementGuid>a5f9562f-957b-4f6d-b267-28fcd96552af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Playing in - JAKARTA')]</value>
      <webElementGuid>d4c3b013-57a7-451e-b111-b96472dcbdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Playing in - JAKARTA']/parent::*</value>
      <webElementGuid>f01f4b9c-de73-4423-8bcd-40f5abc62a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'gui.list_city.php?sid=')]</value>
      <webElementGuid>630636dc-1833-4ac8-9d72-fe22aee14f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a</value>
      <webElementGuid>7a406ab3-de37-4080-aa20-54978e24de51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'gui.list_city.php?sid=' and (text() = 'Playing in - JAKARTA' or . = 'Playing in - JAKARTA')]</value>
      <webElementGuid>da6daf96-5020-45d1-97d0-3c43743b1696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
