<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JOGJA CITY XXI</name>
   <tag></tag>
   <elementGuidId>8c5bd32e-cf81-4650-a4d5-1b74f170693b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='id'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>567ce3c4-644a-434d-adba-7bccc728a127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>79fc2977-a163-4b55-9e89-5d8285a94ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='gui.schedule.php?sid=&amp;find_by=1&amp;cinema_id=YGYJOCI&amp;movie_id=';</value>
      <webElementGuid>2a341644-21e7-4d22-854d-c318196cc2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JOGJA CITY XXI</value>
      <webElementGuid>34c075e5-72cf-4727-bb23-780aecaa504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/div[@class=&quot;all&quot;]/li[@class=&quot;list-group-item&quot;]/div[@id=&quot;id&quot;]</value>
      <webElementGuid>a60006fc-dc72-44b9-bd0e-0ab2dbb835b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='id'])[6]</value>
      <webElementGuid>0c624b5a-8e41-4a46-9aaa-b089c2da262d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ini']/div[3]/li[3]/div</value>
      <webElementGuid>65de6ca5-e3bc-4f25-9f6d-31c7df730eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPIRE XXI'])[1]/following::div[1]</value>
      <webElementGuid>5d62226c-268b-4055-9a5c-b8e95f99d202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SLEMAN CITY HALL XXI'])[1]/preceding::div[1]</value>
      <webElementGuid>2246ee77-6bd1-41f1-be7e-59ca338b86d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JOGJA CITY XXI']/parent::*</value>
      <webElementGuid>84afcdd5-ae65-4a79-8a08-0d4c7e057893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li[3]/div</value>
      <webElementGuid>235ef5bf-c5fd-4196-823a-bf880087dec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id' and (text() = 'JOGJA CITY XXI' or . = 'JOGJA CITY XXI')]</value>
      <webElementGuid>9023fed9-c777-46ce-832a-c29cbeba15e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
