<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YOGYAKARTA</name>
   <tag></tag>
   <elementGuidId>b0816f61-2d90-46dc-bd9f-3e7e7a3cdd46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;location.href='gui.list_theater.php?sid=&amp;city_id=23';&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e83e71a-ed4b-45a2-add7-53a64b8e4dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='gui.list_theater.php?sid=&amp;city_id=23';</value>
      <webElementGuid>b59a514a-3b87-417e-a02e-50f733a13eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YOGYAKARTA</value>
      <webElementGuid>3e67532c-a5e8-46a5-b43c-075e52c240fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ini&quot;)/li[@class=&quot;list-group-item&quot;]/div[1]</value>
      <webElementGuid>cdcd618d-48cf-4073-bba1-756f59019850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;location.href='gui.list_theater.php?sid=&amp;city_id=23';&quot;]</value>
      <webElementGuid>5e5ff556-3a5e-4496-8f92-da67e5b3fa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ini']/li[56]/div</value>
      <webElementGuid>ca08db23-04ef-4f4a-99f5-0947aab1e157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERNATE'])[1]/following::div[1]</value>
      <webElementGuid>40fd497a-2914-416f-bd2f-073efa157c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TASIKMALAYA'])[1]/following::div[2]</value>
      <webElementGuid>87ba8d8b-012f-4284-85f9-9a2c5dd5a362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::div[3]</value>
      <webElementGuid>e12e4671-d7f3-4f2d-9cb6-64d1aa19e441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YOGYAKARTA']/parent::*</value>
      <webElementGuid>677660a2-116c-48d2-8815-7c6e3c825117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[56]/div</value>
      <webElementGuid>2631aaa9-5d21-4a13-9666-953549f97937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'YOGYAKARTA' or . = 'YOGYAKARTA')]</value>
      <webElementGuid>d7c44271-4a8e-41ec-b77d-f668b3b4bfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
