<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_D17_23JWX2</name>
   <tag></tag>
   <elementGuidId>62f161b2-77e4-4577-a19a-6263389d9620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#23JWX2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23JWX2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f6b6e2b9-d8e7-4fd7-b601-ad6dde86b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23JWX2</value>
      <webElementGuid>6cecc450-7dfe-4f24-9658-260351882fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/23JWX2.jpg</value>
      <webElementGuid>1a340fba-1470-42f7-be4c-fa31ee42ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23JWX2&quot;)</value>
      <webElementGuid>34175821-cd65-4900-9bee-d9ee99543241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23JWX2']</value>
      <webElementGuid>8abe4833-1706-41c8-ad65-ca475333fa1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/23JWX2.jpg')]</value>
      <webElementGuid>3cdb741d-85b4-455b-aabd-d4349b69e402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/a/img</value>
      <webElementGuid>db8fa431-9af4-4432-bfd9-5107a143a127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23JWX2' and @src = 'https://web3.21cineplex.com/movie-images/23JWX2.jpg']</value>
      <webElementGuid>068dec8a-d14d-4669-bcf2-2224d66f5fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
