<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SU_13JJUN</name>
   <tag></tag>
   <elementGuidId>db2798f7-7d98-4cc4-b3ba-e80908a75b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#13JJUN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='13JJUN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2317b34a-72ab-438f-9e79-b8d0d4328a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13JJUN</value>
      <webElementGuid>cd00ba3d-cba7-4056-b6ea-c60305726584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.21cineplex.com/movie-images/13JJUN.jpg</value>
      <webElementGuid>0d91c374-64bd-4dd4-8b84-dd7e12c347f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13JJUN&quot;)</value>
      <webElementGuid>bcc7dad7-9a6f-4b8d-9b24-92ccf51b7204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='13JJUN']</value>
      <webElementGuid>d7d7c436-59f5-47ed-905a-7fe533b8b752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://web3.21cineplex.com/movie-images/13JJUN.jpg')]</value>
      <webElementGuid>2faadd64-ad82-440f-9699-71f74dc9f668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>6855e58c-d5e5-41fa-b499-62cdf7a2cc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '13JJUN' and @src = 'https://web3.21cineplex.com/movie-images/13JJUN.jpg']</value>
      <webElementGuid>294e9e06-70e7-4059-bf9d-508142469bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
